generated_at: '2026-02-02 16:51:06'
source_master: C:\Users\user\Desktop\Git\ark-blueprints\data\processed\master.csv
n_rows: 381708
n_cols: 163
columns:
- player_id
- AB_class
- age
- weight
- team
- origin
- run_once
- F
- L
- ST_mean
- N_winning_rate
- N_2rentai_rate
- N_3rentai_rate
- LC_winning_rate
- LC_2rentai_rate
- LC_3rentai_rate
- motor_number
- motor_2rentai_rate
- motor_3rentai_rate
- boat_number
- boat_2rentai_rate
- boat_3rentai_rate
- pred_mark
- race_name
- precondition_1
- precondition_2
- race_id
- date
- code
- R
- timetable
- entry_tenji
- ST_tenji
- counter_weight
- time_tenji
- Tilt
- propeller
- parts_exchange
- temperature
- weather
- wind_speed
- wind_direction
- water_temperature
- wave_height
- winning_trick
- henkan_ticket
- remarks
- rank
- wakuban
- player
- entry
- ST
- ST_rank
- sex
- place
- race_grade
- race_type
- race_attribute
- title
- day
- section
- schedule
- is_wakunari
- section_id
- __source_file
- ST_tenji_rank
- is_top2
- season_q
- tenji_mu
- tenji_sd
- n_tenji
- tenji_resid
- tenji_z
- tenji_resid_rank
- tenji_z_rank
- tenji_resid_top1
- tenji_resid_top2
- n_finished
- p1
- p2
- p3
- p4
- p5
- p6
- base_p1
- base_p2
- base_p3
- base_p4
- base_p5
- base_p6
- adv_p1
- adv_p2
- adv_p3
- adv_p4
- adv_p5
- adv_p6
- lr_p1
- lr_p2
- lr_p3
- lr_p4
- lr_p5
- lr_p6
- n_win
- p_nige
- p_sashi
- p_makuri
- p_makurizashi
- p_nuki
- p_megumare
- base_p_nige
- base_p_sashi
- base_p_makuri
- base_p_makurizashi
- base_p_nuki
- base_p_megumare
- adv_p_nige
- adv_p_sashi
- adv_p_makuri
- adv_p_makurizashi
- adv_p_nuki
- adv_p_megumare
- lr_p_nige
- lr_p_sashi
- lr_p_makuri
- lr_p_makurizashi
- lr_p_nuki
- lr_p_megumare
- finish1_flag_cur
- finish2_flag_cur
- finish3_flag_cur
- finish1_rate_last10_entry
- finish1_cnt_last10_entry
- finish2_rate_last10_entry
- finish2_cnt_last10_entry
- finish3_rate_last10_entry
- finish3_cnt_last10_entry
- st_mean_last10_entry
- st_std_last10_entry
- finish1_rate_last10_waku
- finish1_cnt_last10_waku
- finish2_rate_last10_waku
- finish2_cnt_last10_waku
- finish3_rate_last10_waku
- finish3_cnt_last10_waku
- st_mean_last10_waku
- st_std_last10_waku
- ST_timing
- ST_mean_current
- ST_rank_current
- ST_previous_time
- boat_color
- entry_history
- race_ct_current
- rank_history
- score
- score_rate
- ranking_point
- ranking_point_sum
- ranking_point_rate
- condition_point
- condition_point_sum
- condition_point_rate
- motor_id
